global:
  scrape_interval: 10s
  evaluation_interval: 10s
  external_labels:
    monitor: 'prometheus'

scrape_configs:

  - job_name: urlshortner-service
    honor_labels: true
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - service:8081
