{
 "title": "Shortner service overview",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Redirects",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(request_counter{status=\"302\"})",
     "legendFormat": "redirects"
    }
   ]
  },
  {
   "title": "Requests per second (successes and errors) Stacked",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(request_counter{status=~\"2.*|3.*|404\"}[1m]))>0",
     "legendFormat": "Success responses"
    },
    {
     "expr": "sum(rate(request_counter{status!~\"2.*|3.*|404|5.*\"}[1m]))",
     "legendFormat": "4xx responses"
    },
    {
     "expr": "sum(rate(request_counter{status=~\"5.*\"}[1m]))>0",
     "legendFormat": "5xx responses"
    }
   ]
  },
  {
   "title": "store urls",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(request_counter{status=\"200\", path=\"/\"})"
    }
   ]
  },
  {
   "title": "Redirect API response times",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(application_requests_latency_bucket{path=\"/{code:.*}\", method=\"GET\"}[2m])) by(le, path))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(application_requests_latency_bucket{path=\"/{code:.*}\", method=\"GET\"}[2m])) by(le, path))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(application_requests_latency_bucket{path=\"/{code:.*}\", method=\"GET\"}[2m])) by(le, path))",
     "legendFormat": "p75"
    }
   ]
  },
  {
   "title": "Store API response times",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 10 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(application_requests_latency_bucket{path=\"/\", method=\"POST\"}[2m])) by(le, path))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(application_requests_latency_bucket{path=\"/\", method=\"POST\"}[2m])) by(le, path))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(application_requests_latency_bucket{path=\"/\", method=\"POST\"}[2m])) by(le, path))",
     "legendFormat": "p75"
    }
   ]
  }
 ]
}